apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gubernat-tests-dev

resources:
- namespace.yaml
- deployment.yaml
- ingress-https.yaml
- ingress.yaml
- svc.yaml

{% if repo_mirror is defined %}
images:
- name: quay.io/pflaeging/httpbin:latest-multiarch
  newName: {{ repo_mirror }}/quay.io/pflaeging/httpbin:latest-multiarch
  newTag: latest-multiarch
{% endif %}
